title: Swaroop Panda
url: "https://panda-swaroop.github.io/"
baseurl: ""

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

tracking_id: #

sass:
    style: compressed
    sass_dir: _sass
